### ISSUE TITLE
Add ability to change variable name of output

### ISSUE THREAD

**Issue by tonyrafter** [climate-innovation-hub/frequency-analysis#15]
Current code doesn't have the ability to change the name of the variable being analysed to its 'extreme' variable equivalent. This is most important for variables where we may be interested in both the maxima and minima. For example, we might be interested in both extreme low overnight temps (aka `tnn`) and extreme warm nights (`tnx`), which both use the `tmin` variable.

At the moment I think the code takes a supplied variable and uses this as the output variable as well. This becomes an issue when you want to look at both mins and maxes (e.g. `tnn` and `tnx`) as the output variable names and metadata are identical. The output file name can be supplied with a different 'extreme' variable name, but then there is a mismatch with the variable name within the file.

I'm not quite sure how to fix this at present. I was thinking to add an output variable name as a command line arg, keeping most of the metadata from the 'parent' variable and changing e.g. `standard_name` to suit the new 'extreme' variable. 

I can make an attempt at a fix for this but I might need a code review - or some help?

**Comment by DamienIrving** [comment]
Adding this functionality sounds like a good idea to me.

At the moment xclim adds a whole bunch of variable attributes - many of which duplicate the same information - so while we're at it we might want to think about which of them we want to actually keep. e.g.

![Screenshot 2023-04-26 at 6 19 22 pm](https://user-images.githubusercontent.com/2062210/234716459-a0eae943-329f-4795-8ce6-065a0127f65b.png)

I'd suggest we could delete:
- `cell_methods`: because no idea what `dparams: ppf` even means
- `method`: it's mentioned elsewhere that Maximum Likelihood was used
- `history`: having a variable attribute called history is sometimes problematic if you've also got a global attribute called history (we can add `xclim_version` as a global file attribute to capture that information)
- `long_name` could be replaced with the contents of `original_long_name`: because the `long_name` they provide gives no information that isn't provided elsewhere

We could also add:
- `block_freq`: corresponding to the `--time_freq` input argument
- `season` (optional): corresponding to the `--season` input argument
- `months` (optional): corresponding to the `--month` input argument

So we'd end up with something like these variable attributes:
```
tasmin(ari, lat, lon)
    tasmin:long_name = "Daily Minimum Near-Surface Air Temperature" ;
    tasmin:standard_name = "air_temperature" ;
    tasmin:units = "degC" ;
    tasmin:description = "ARIs estimated by the genextreme distribution" ;
    tasmin:estimator = "Maximum likelihood" ;
    tasmin:scipy_dist = "genextreme" ;
    tasmin:block_freq = "A-JUN" ;
```
(note the small edit to `description` to say ARIs instead of quantiles)

Plus a global attribute that says:
```
xclim_version = "0.39.0"
```

We could then also make it so the output `var_name`, `standard_name` and `long_name` can be altered from the default by optional command line arguments.

How does that all sound?

**Comment by tonyrafter** [comment]
That all sounds good, particularly the reduction in these superfluous variable metadata fields. 

I'd just add that there are a limited number of variables for us to analyse, so we could set up a function to take an input variable and the 'mode' to determine the appropriate index/extreme variable name. For example, getting `max` of tasmax would give `txx`, looking at `min` would be `txn` etc., perhaps with associated changes in the `long_name` (e.g. 'Maxima of Daily Minimum Near-Surface Air Temperature')?

On the other hand - if this is getting too complicated we can always use cdo/nco tools to post-process... (Although this is not as neat an option, it will work quickly!)
